[package]
name = "mdreplace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mdreplace"
crate-type = ["cdylib"]

[dependencies]
ecow = "0.1.1"
pyo3 = "0.19.0"
unscanny = "0.1.0"
